open import "../../futsource/everything"

let input =
  let pft = Pft(0)
  let pft = pft with phenology = 1

  in pft

-- Autogenerated test of alphaa output result field: result
-- ==
-- entry: result_test
-- input {}
-- output { 0.650000 }

entry result_test =
  let result = alphaa input
  in result

