open import "../../futsource/everything"

let input =
  let pft = Pft(0)
  let pft = pft with pstemp_max = 55.000000
  let pft = pft with pstemp_high = 30.000000
  let pft = pft with pstemp_low = 25.000000
  let pft = pft with pstemp_min = 2.000000
  let pft = pft with pathway = 1
  let pft = pft with phenology = 1
  let pft = pft with lambda_max = 0.800000
  let pft = pft with lifeform = 1

  let co2 : f64 = 296.378
  let temp : f64 = 28.1906
  let par : f64 = 1.08646e+07
  let daylength : f64 = 11.9855
  let fpar : f64 = 0.0200921
  let fpc : f64 = 0.00998246
  let gcbase : f64 = 0.0138784
  let vmax : f64 = 5.34183
  let nactive : f64 = 6.46219e-05
  let ifnlimvmax : bool = true
  let moss_wtp_limit : f64 = 1
  let graminoid_wtp_limit : f64 = 1
  let inund_stress : f64 = 1
  in (pft, co2, temp, par, daylength, fpar, fpc, gcbase, vmax, nactive, ifnlimvmax, moss_wtp_limit, graminoid_wtp_limit, inund_stress)

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: agd_g
-- ==
-- entry: agd_g_test
-- input {}
-- output { 0.043229 }

entry agd_g_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.agd_g

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: adtmm
-- ==
-- entry: adtmm_test
-- input {}
-- output { 0.006710 }

entry adtmm_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.adtmm

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: rd_g
-- ==
-- entry: rd_g_test
-- input {}
-- output { 0.080127 }

entry rd_g_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.rd_g

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: vm
-- ==
-- entry: vm_test
-- input {}
-- output { 5.341827 }

entry vm_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.vm

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: je
-- ==
-- entry: je_test
-- input {}
-- output { 0.005583 }

entry je_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.je

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: nactive_opt
-- ==
-- entry: nactive_opt_test
-- input {}
-- output { 0.000207 }

entry nactive_opt_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.nactive_opt

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: vmaxnlim
-- ==
-- entry: vmaxnlim_test
-- input {}
-- output { 1.000000 }

entry vmaxnlim_test =
  let (phot_result, lambda) = assimilation_wstress input
  in phot_result.vmaxnlim

-- Autogenerated test of assimilation_wstress output (phot_result, lambda) field: lambda
-- ==
-- entry: lambda_test
-- input {}
-- output { 0.221094 }

entry lambda_test =
  let (phot_result, lambda) = assimilation_wstress input
  in lambda

