open import "../../futsource/everything"

let input =
  let date = Date()
  let soiltype = Soiltype(0)
  let (_, _, stand) = Stand(0,0,0,0,0,0,date)
  let stand = stand with landcover = 4
  let gridcell = Gridcell()
  let gridcell = gridcell with lat = 19.799999
  let pft = Pft(0)
  let pft = pft with lifeform = 1
  let soil = Soil(soiltype)
  let soil = soil with acro_co2 = 934.000000
  let climate = Climate(0.0, 0, 0)
  let climate = climate with co2 = 296.378500
  in (climate, pft, stand, soil, gridcell)

-- Autogenerated test of get_co2 output pftco2 field: pftco2
-- ==
-- entry: pftco2_test
-- input {}
-- output { 296.378500 }

entry pftco2_test =
  let pftco2 = get_co2 input
  in pftco2

