open import "../../futsource/everything"

let input =
  let stand = Stand()
  let stand = stand with is_highlatitude_peatland_stand = false

  let soil = Soil()
  let soil = soil with acro_co2 = 934.000000

  let climate = Climate()
  let climate = climate with co2 = 296.378500

  in pftco2

-- Autogenerated test of get_co2 output pftco2 field: pftco2
-- ==
-- entry: pftco2_test
-- input {}
-- output { 296.378500 }

entry pftco2_test =
  let pftco2 = get_co2 input
  in pftco2

