open import "../../futsource/everything"

let input =
  let ps_env = PhotosynthesisEnvironment()
  let ps_env = ps_env with temp = 21.794977
  let ps_env = ps_env with co2 = 296.378500
  let ps_env = ps_env with fpar = 1.000000
  let ps_env = ps_env with par = 7307193.574951
  let ps_env = ps_env with daylength = 10.826868

  let ps_stresses = PhotosynthesisStresses()
  let ps_stresses = ps_stresses with ifnlimvmax = false
  let ps_stresses = ps_stresses with moss_ps_limit = 1.000000
  let ps_stresses = ps_stresses with graminoid_ps_limit = 1.000000
  let ps_stresses = ps_stresses with inund_stress = 1.000000

  let pft = Pft()
  let pft = pft with pstemp_max = 55.000000
  let pft = pft with pstemp_high = 30.000000
  let pft = pft with pstemp_low = 25.000000
  let pft = pft with pstemp_min = 2.000000
  let pft = pft with lifeform = 1

  let lambda : f64 = 0.8
  let nactive : f64 = 1
  let vm : f64 = -1
  in (ps_env, ps_stresses, pft, lambda, nactive, vm)

-- Autogenerated test of photosynthesis output agd_g
-- ==
-- entry: agd_g_test
-- input {}
-- output { 11.010272 }

entry agd_g_test =
  (photosynthesis input).agd_g

-- Autogenerated test of photosynthesis output adtmm
-- ==
-- entry: adtmm_test
-- input {}
-- output { 20.006328 }

entry adtmm_test =
  (photosynthesis input).adtmm

-- Autogenerated test of photosynthesis output rd_g
-- ==
-- entry: rd_g_test
-- input {}
-- output { 2.704240 }

entry rd_g_test =
  (photosynthesis input).rd_g

-- Autogenerated test of photosynthesis output vm
-- ==
-- entry: vm_test
-- input {}
-- output { 180.282661 }

entry vm_test =
  (photosynthesis input).vm

-- Autogenerated test of photosynthesis output je
-- ==
-- entry: je_test
-- input {}
-- output { 1.248118 }

entry je_test =
  (photosynthesis input).je

-- Autogenerated test of photosynthesis output nactive_opt
-- ==
-- entry: nactive_opt_test
-- input {}
-- output { 0.012033 }

entry nactive_opt_test =
  (photosynthesis input).nactive_opt

-- Autogenerated test of photosynthesis output vmaxnlim
-- ==
-- entry: vmaxnlim_test
-- input {}
-- output { 1.000000 }

entry vmaxnlim_test =
  (photosynthesis input).vmaxnlim

