open import "../../futsource/everything"

let input =
  let ps_env = PhotosynthesisEnvironment()
  let ps_env = ps_env with temp = 21.794977
  let ps_env = ps_env with co2 = 296.378500
  let ps_env = ps_env with fpar = 1.000000
  let ps_env = ps_env with par = 7307193.574951
  let ps_env = ps_env with daylength = 10.826868

  let ps_stresses = PhotosynthesisStresses()
  let ps_stresses = ps_stresses with ifnlimvmax = false
  let ps_stresses = ps_stresses with moss_ps_limit = 1.000000
  let ps_stresses = ps_stresses with graminoid_ps_limit = 1.000000
  let ps_stresses = ps_stresses with inund_stress = 1.000000

  let pft = Pft()
  let pft = pft with pstemp_max = 55.000000
  let pft = pft with pstemp_high = 30.000000
  let pft = pft with pstemp_low = 25.000000
  let pft = pft with pstemp_min = 2.000000
  let pft = pft with lifeform = 1

  let lambda : f64 = 0.8
  let nactive : f64 = 1
  let vm : f64 = -1
  in (ps_env, ps_stresses, pft, lambda, nactive, vm)

-- Autogenerated test of photosynthesis output ps_result field: agd_g
-- ==
-- entry: agd_g_test
-- input {}
-- output { 11.010272 }

entry agd_g_test =
  let ps_result = photosynthesis input
  in ps_result.agd_g

-- Autogenerated test of photosynthesis output ps_result field: adtmm
-- ==
-- entry: adtmm_test
-- input {}
-- output { 20.006328 }

entry adtmm_test =
  let ps_result = photosynthesis input
  in ps_result.adtmm

-- Autogenerated test of photosynthesis output ps_result field: rd_g
-- ==
-- entry: rd_g_test
-- input {}
-- output { 2.704240 }

entry rd_g_test =
  let ps_result = photosynthesis input
  in ps_result.rd_g

-- Autogenerated test of photosynthesis output ps_result field: vm
-- ==
-- entry: vm_test
-- input {}
-- output { 180.282661 }

entry vm_test =
  let ps_result = photosynthesis input
  in ps_result.vm

-- Autogenerated test of photosynthesis output ps_result field: je
-- ==
-- entry: je_test
-- input {}
-- output { 1.248118 }

entry je_test =
  let ps_result = photosynthesis input
  in ps_result.je

-- Autogenerated test of photosynthesis output ps_result field: nactive_opt
-- ==
-- entry: nactive_opt_test
-- input {}
-- output { 0.012033 }

entry nactive_opt_test =
  let ps_result = photosynthesis input
  in ps_result.nactive_opt

-- Autogenerated test of photosynthesis output ps_result field: vmaxnlim
-- ==
-- entry: vmaxnlim_test
-- input {}
-- output { 1.000000 }

entry vmaxnlim_test =
  let ps_result = photosynthesis input
  in ps_result.vmaxnlim

