open import "../../futsource/everything"

let input =
  let gtemp_air : f64 = 2.74754
  let gtemp_soil : f64 = 2.61082
  let lifeform : enum_type = 1
  let respcoeff : f64 = 0.268437
  let cton_sap : f64 = 486.781
  let cton_root : f64 = 81.8356
  let cmass_sap : f64 = 0.00820986
  let cmass_root_today : f64 = 0.00305841
  let assim : f64 = 0
  in (gtemp_air, gtemp_soil, lifeform, respcoeff, cton_sap, cton_root, cmass_sap, cmass_root_today, assim)

-- Autogenerated test of respiration output resp field: resp
-- ==
-- entry: resp_test
-- input {}
-- output { 0.000004 }

entry resp_test =
  let resp = respiration input
  in resp

